// Base de datos de compatibilidad y repuestos para MediBridge
const COMPATIBILITY_DATABASE = {
    brands: {
        "Philips": ["iE33", "iU22", "CX50 Portable", "Affiniti 50", "Affiniti 70", "EPIQ 5", "EPIQ 7", "EPIQ CVx", "ClearVue 350", "ClearVue 550"],
        "GE Healthcare": ["Vivid i", "Vivid q", "Voluson E6", "Voluson E8", "Voluson E10", "Logiq E9", "Logiq P9", "Vivid E9", "Vivid E95"],
        "Samsung / Medison": ["Accuvix A30", "WS80A", "HS70A"]
    },
    parts: [
        // PHILIPS PARTS
        {
            id: "philips-uaio",
            brands: ["Philips"],
            models: ["iE33", "iU22"],
            name: "Módulo UAIO (Unified Analog Input Output)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "PH-UAIO-3322",
            availability: "in-stock",
            availabilityText: "En Stock (Reacondicionado Certificado)",
            condition: "Reacondicionado con Pruebas de Diagnóstico",
            description: "Placa principal UAIO restaurada para sistemas iE33 e iU22. Soluciona fallas comunes de arranque, pantalla negra y fallas en adquisición de señal de imagen."
        },
        {
            id: "philips-dsc",
            brands: ["Philips"],
            models: ["iE33", "iU22"],
            name: "Módulo DSC (Digital Scan Converter)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "PH-DSC-9801",
            availability: "in-stock",
            availabilityText: "En Stock (Garantizado)",
            condition: "Reacondicionado y Calibrado",
            description: "Convertidor digital de escaneo para procesamiento de imagen en tiempo real. Probado en sistemas F-Cart y G-Cart."
        },
        {
            id: "philips-fec",
            brands: ["Philips"],
            models: ["iE33", "iU22"],
            name: "Tarjeta FEC (Front End Controller)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "PH-FEC-4050",
            availability: "low-stock",
            availabilityText: "Stock Limitado (Consultar)",
            condition: "OEM Usado / Probado",
            description: "Tarjeta de control frontal que gestiona la sincronización del haz y el canal de recepción. Probado contra ruidos y artefactos de imagen."
        },
        {
            id: "philips-psu",
            brands: ["Philips"],
            models: ["iE33", "iU22", "Affiniti 50", "Affiniti 70"],
            name: "Fuente de Poder (PSU / Power Supply Unit)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "PH-PSU-450W",
            availability: "in-stock",
            availabilityText: "En Stock (Nuevo & Reacondicionado)",
            condition: "Disponible en OEM Nuevo o Reconstruido",
            description: "Módulo de alimentación completo. Rigurosamente probado bajo cargas de estrés térmico para garantizar estabilidad de voltaje en los rieles analógicos y digitales."
        },
        
        // PHILIPS PORTABLE CX50 PARTS
        {
            id: "philips-cx50-acq",
            brands: ["Philips"],
            models: ["CX50 Portable"],
            name: "Módulo de Adquisición CX50 (Acquisition Module)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "PH-CX50-ACQ",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado Certificado",
            description: "Módulo de adquisición de canales de señal para el ecógrafo portátil premium CX50. Probado y libre de ruidos en imagen Doppler."
        },
        {
            id: "philips-cx50-pwr",
            brands: ["Philips"],
            models: ["CX50 Portable"],
            name: "Tarjeta de Poder CX50 (Power Board)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "PH-CX50-PWR",
            availability: "low-stock",
            availabilityText: "Stock Limitado",
            condition: "Restaurada y Testeada",
            description: "Tarjeta interna de distribución de energía y carga de batería para Philips CX50. Regulación de voltaje de alta fidelidad."
        },
        {
            id: "philips-cx50-mb",
            brands: ["Philips"],
            models: ["CX50 Portable"],
            name: "Tarjeta Madre Principal CX50 (Main Motherboard)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "PH-CX50-MBD",
            availability: "low-stock",
            availabilityText: "Consulte disponibilidad",
            condition: "Usada en óptimas condiciones",
            description: "Tarjeta de procesamiento central que integra CPU y GPU del sistema portátil CX50. Instalación y configuración de software disponible."
        },

        // CARDIOLOGY TRANSDUCERS (PHILIPS)
        {
            id: "transductor-x51",
            brands: ["Philips"],
            models: ["iE33", "EPIQ 7", "EPIQ CVx", "CX50 Portable"],
            name: "Transductor de Matriz Activa xMATRIX X5-1",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-PH-X51",
            availability: "in-stock",
            availabilityText: "En Stock (Garantía de 6 meses)",
            condition: "Reacondicionado de fábrica / Lente excelente",
            description: "Transductor cardíaco xMATRIX 4D de alta densidad para ecocardiografía tridimensional avanzada. Compatible con iE33 (F-Cart/G-Cart), EPIQ y CX50 Portable (conector especial)."
        },
        {
            id: "transductor-s51",
            brands: ["Philips"],
            models: ["iE33", "iU22", "Affiniti 50", "Affiniti 70", "EPIQ 5", "EPIQ 7", "CX50 Portable"],
            name: "Transductor Sectorial S5-1",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-PH-S51",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Excelente estado estético y funcional",
            description: "Transductor sectorial para ecocardiología pediátrica y de adultos. Excelente sensibilidad Doppler y resolución espacial."
        },
        {
            id: "transductor-x72t",
            brands: ["Philips"],
            models: ["iE33", "EPIQ 7", "EPIQ CVx", "CX50 Portable"],
            name: "Transductor Transesofágico (TEE) xMATRIX X7-2t",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-PH-X72T",
            availability: "low-stock",
            availabilityText: "Stock Limitado - Entrega Rápida",
            condition: "Probado contra fugas eléctricas / Desinfectado",
            description: "Transductor TEE cardíaco multiplano 3D para procedimientos intervencionistas pediátricos y adultos en quirófano o sala de hemodinamia."
        },
        {
            id: "transductor-s83",
            brands: ["Philips"],
            models: ["iE33", "EPIQ 7", "CX50 Portable"],
            name: "Transductor Sectorial Pediátrico S8-3",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-PH-S83",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado con Test First-Call",
            description: "Transductor sectorial cardíaco para pacientes pediátricos y neonatales grandes. Rango de frecuencia expandido."
        },
        {
            id: "transductor-s124",
            brands: ["Philips"],
            models: ["iE33", "EPIQ 7", "CX50 Portable"],
            name: "Transductor Sectorial Neonatal S12-4",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-PH-S124",
            availability: "low-stock",
            availabilityText: "Stock Limitado",
            condition: "Excelente estado acústico",
            description: "Sonda sectorial de ultra alta frecuencia para ecocardiografía neonatal e infantil en cuidados intensivos."
        },
        {
            id: "transductor-c51",
            brands: ["Philips"],
            models: ["iU22", "Affiniti 50", "Affiniti 70", "EPIQ 5", "EPIQ 7"],
            name: "Transductor Convexo C5-1 PureWave",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-PH-C51",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado con Test First-Call",
            description: "Transductor convexo con tecnología PureWave para imagen abdominal y obstétrica en pacientes difíciles. 100% libre de cristales muertos."
        },
        {
            id: "transductor-l125",
            brands: ["Philips"],
            models: ["iU22", "Affiniti 50", "Affiniti 70", "EPIQ 5", "EPIQ 7", "CX50 Portable"],
            name: "Transductor Lineal L12-5",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-PH-L125",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado",
            description: "Transductor lineal de alta resolución para partes pequeñas, vascular y pediatría. Lente acústica y cable impecables."
        },
        
        // GE HEALTHCARE & PORTABLE VIVID I/Q PARTS
        {
            id: "ge-rf-board",
            brands: ["GE Healthcare"],
            models: ["Voluson E6", "Voluson E8", "Voluson E10"],
            name: "Tarjeta RF Board (Procesamiento de Radiofrecuencia)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "GE-RF-VOL8",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado Certificado",
            description: "Tarjeta RF de digitalización y procesamiento de canales para sistemas Voluson Expert. Soluciona líneas en pantalla e interferencias."
        },
        {
            id: "ge-multiplexer",
            brands: ["GE Healthcare"],
            models: ["Voluson E8", "Logiq E9"],
            name: "Tarjeta de Transductores (Multiplexer Board / Probe Select)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "GE-MUX-9900",
            availability: "low-stock",
            availabilityText: "Stock Limitado",
            condition: "Usado Probado",
            description: "Tarjeta selectora de puertos de transductor. Resuelve fallas de reconocimiento intermitente de sondas y ruidos en la imagen."
        },
        {
            id: "ge-power-assembly",
            brands: ["GE Healthcare"],
            models: ["Voluson E6", "Voluson E8", "Logiq E9"],
            name: "Fuente de Alimentación (Power Assembly)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "GE-PWR-VOL8",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado / Nuevos Capacitores",
            description: "Fuente de poder de alta potencia reacondicionada con componentes de larga duración. Probada bajo carga máxima."
        },
        {
            id: "ge-vivid-fe",
            brands: ["GE Healthcare"],
            models: ["Vivid i", "Vivid q"],
            name: "Tarjeta de Procesamiento FE (Front End Board - Vivid i/q)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "GE-VIV-FE",
            availability: "low-stock",
            availabilityText: "Stock Limitado",
            condition: "Reacondicionado con Pruebas de Diagnóstico",
            description: "Tarjeta de front-end para digitalización de canales en ecógrafos portátiles Vivid i y Vivid q de cardiología."
        },
        {
            id: "ge-vivid-dc",
            brands: ["GE Healthcare"],
            models: ["Vivid i", "Vivid q"],
            name: "Fuente de Alimentación Interna DC-DC (Power Board Vivid i)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "GE-VIV-PWR",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado",
            description: "Módulo de conversión de energía interna para los portátiles Vivid i y Vivid q. Estabiliza el voltaje analógico del sistema."
        },

        // CARDIOLOGY TRANSDUCERS (GE HEALTHCARE)
        {
            id: "transductor-3srs",
            brands: ["GE Healthcare"],
            models: ["Vivid i", "Vivid q", "Vivid E9", "Logiq E9"],
            name: "Transductor Cardiaco Sectorial 3S-RS",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-GE-3SRS",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado con Test First-Call",
            description: "Transductor sectorial de adultos para cardiología y ecocardiografía transcraneal. Conector tipo RS para portátiles y consolas."
        },
        {
            id: "transductor-m4srs",
            brands: ["GE Healthcare"],
            models: ["Vivid i", "Vivid q", "Vivid E9", "Vivid E95"],
            name: "Transductor Sectorial de Matriz Activa M4S-RS",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-GE-M4SRS",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Excelente estado físico y funcional",
            description: "Transductor de matriz sectorial cardíaco avanzado para adultos, que proporciona una definición y resolución espacial premium."
        },
        {
            id: "transductor-6srs",
            brands: ["GE Healthcare"],
            models: ["Vivid i", "Vivid q", "Vivid E9"],
            name: "Transductor Sectorial Pediátrico 6S-RS",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-GE-6SRS",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado",
            description: "Sonda sectorial cardíaca para ecocardiografía pediátrica. Alta sensibilidad Doppler y resolución de contraste."
        },
        {
            id: "transductor-9trs",
            brands: ["GE Healthcare"],
            models: ["Vivid i", "Vivid q", "Vivid E9"],
            name: "Transductor Transesofágico (TEE) Multiplano 9T-RS",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-GE-9TRS",
            availability: "low-stock",
            availabilityText: "Stock Limitado (Consultar)",
            condition: "Probado de seguridad eléctrica contra fugas",
            description: "Transductor transesofágico cardíaco multiplano para ecocardiografía diagnóstica intervencionista de adultos."
        },
        {
            id: "transductor-rab6d",
            brands: ["GE Healthcare"],
            models: ["Voluson E6", "Voluson E8", "Voluson E10"],
            name: "Transductor Convexo Volumétrico 4D RAB6-D",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-GE-RAB6D",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado / Domo y Aceite Nuevos",
            description: "Transductor convexo 4D liviano de banda ancha para diagnóstico prenatal y ginecología. Recubrimiento exterior e interno restaurado a especificaciones OEM."
        },
        {
            id: "transductor-11ld",
            brands: ["GE Healthcare"],
            models: ["Voluson E8", "Voluson E10", "Logiq E9", "Vivid E9"],
            name: "Transductor Lineal 11L-D",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-GE-11LD",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Excelente Estado",
            description: "Sonda lineal para mama, vascular superficial y tiroides. Garantía de rendimiento e imagen de alta fidelidad."
        },
        {
            id: "transductor-ric59d",
            brands: ["GE Healthcare"],
            models: ["Voluson E6", "Voluson E8", "Voluson E10"],
            name: "Transductor Endocavitario 4D RIC5-9-D",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-GE-RIC59D",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado / Cúpula Perfecta",
            description: "Transductor endocavitario volumétrico 4D para estudios transvaginales y ginecológicos tempranos. Probado en hermeticidad y movimiento mecánico."
        },

        // SAMSUNG MEDISON PARTS
        {
            id: "samsung-mainboard",
            brands: ["Samsung / Medison"],
            models: ["Accuvix A30", "WS80A"],
            name: "Tarjeta Principal (Main Board)",
            category: "electronics",
            categoryName: "Repuestos Electrónicos",
            sku: "SAM-MB-A30",
            availability: "on-demand",
            availabilityText: "Bajo Pedido (Importación 3-5 días)",
            condition: "OEM Original",
            description: "Placa base del sistema que integra CPU y procesamiento digital. Garantiza restauración completa del sistema de software."
        },
        {
            id: "transductor-cv18ad",
            brands: ["Samsung / Medison"],
            models: ["Accuvix A30", "WS80A"],
            name: "Transductor Convexo Volumétrico 4D CV1-8AD",
            category: "transducers",
            categoryName: "Transductores",
            sku: "TX-SAM-CV18",
            availability: "in-stock",
            availabilityText: "En Stock",
            condition: "Reacondicionado",
            description: "Transductor obstétrico volumétrico 3D/4D de alta definición. Cable, conector y domo acústico validados contra ruidos."
        }
    ]
};
